Move some stuff to query package in a way compatible with #96 Committing WIP to get debugging help.
unit tests fixed, first pass at actual query code

Remove summary code which was generating a fascinating Heisenbug

Check this out:

$ git rev-parse --short HEAD && go test ./pkg/ndau -run TestCanQuerySummary2 && go test
./pkg/ndau
Fri Oct 12 14:38:52 CEST 2018
a63e19a
ok  github.com/oneiro-ndev/ndau/pkg/ndau0.683s
--- FAIL: TestCanQuerySummary2 (0.00s)
require.go:157:
Error Trace:app_query_test.go:101
Error:      Not equal:
            expected: "total ndau at height 1 is 1000100000000, in 2 accounts"
            actual  : "total ndau at height 1 is 1000000000000, in 1 accounts"

            Diff:
            --- Expected
            +++ Actual
            @@ -1 +1 @@
            -total ndau at height 1 is 1000100000000, in 2 accounts
            +total ndau at height 1 is 1000000000000, in 1 accounts
Test:       TestCanQuerySummary2
FAIL
FAILgithub.com/oneiro-ndev/ndau/pkg/ndau1.544s

No idea what was going on there, but taking out the code under test fixes it.